"""empty message

Revision ID: 00c6daf0d96c
Revises: ec67f2653f20
Create Date: 2018-12-01 11:06:51.837317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c6daf0d96c'
down_revision = 'ec67f2653f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_ta_fkey', 'log', type_='foreignkey')
    op.drop_column('log', 'ta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('ta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('log_ta_fkey', 'log', 'user', ['ta'], ['id'])
    # ### end Alembic commands ###
