"""empty message

Revision ID: 3744011972c4
Revises: 4ffa4479924e
Create Date: 2018-11-30 20:39:35.953322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3744011972c4'
down_revision = '4ffa4479924e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutoring_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ta', sa.Integer(), nullable=True),
    sa.Column('started', sa.DateTime(), nullable=True),
    sa.Column('ended', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ta'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutoring_session')
    # ### end Alembic commands ###
