"""empty message

Revision ID: 550725ddebe3
Revises: 9e8f3e65fda8
Create Date: 2018-11-27 15:31:11.121545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550725ddebe3'
down_revision = '9e8f3e65fda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('role', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('role', sa.Column('name', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'role', ['name'])
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'confirmed_at')
    op.drop_column('user', 'active')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'name')
    op.drop_column('role', 'description')
    op.drop_table('roles_users')
    # ### end Alembic commands ###
