"""empty message

Revision ID: ec67f2653f20
Revises: 3744011972c4
Create Date: 2018-12-01 11:02:54.072473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec67f2653f20'
down_revision = '3744011972c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('session', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'log', 'tutoring_session', ['session'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.drop_column('log', 'session')
    # ### end Alembic commands ###
